pipeline:
  domain: procurement
  layer: bronze

source:
  entity: lfb1
  sub_folder: lfb1
  format: csv
  header: true

target:
  schema: bronze
  table: vendorCompany

partition:
  columns:
    - _ingest_date

options:
  schema_evolution_mode: addNewColumns
  infer_column_types: false