pipeline:
  domain: procurement
  layer: bronze

source:
  entity: lfa1
  sub_folder: lfa1
  format: csv
  header: true

target:
  schema: bronze
  table: vendor

partition:
  columns:
    - _ingest_date

options:
  schema_evolution_mode: addNewColumns
  infer_column_types: false
  max_files_per_trigger: 100