domain: procurement
entity: lfb1
format: csv
catalog: workspace

schemas:
  bronze: bronze
  silver: silver

keys:
  primary: vendor_id

tables:
  bronze_table: vendorCompany
  silver_table: cleansed_vendorCompany

  cdm_table: vendorCompany_cdm

scd:
  type: 2
  sequence_column: _ingest_ts
  track_history_columns:
    - company_code
    - reconciliation_account
    - payment_terms
    - payment_method
    - planning_group
    - created_date
    - price
  audit_columns:
    start_date: __START_AT
    end_date: __END_AT
    is_current: is_current
