domain: procurement
entity: lfa1
format: csv
catalog: workspace

schemas:
  bronze: bronze
  silver: silver

keys:
  primary: vendor_id

tables:
  bronze_table: vendor
  silver_table: cleansed_vendor
  cdm_table: vendor_cdm

scd:
  type: 2
  sequence_column: _ingest_ts
  track_history_columns:
    - vendor_name
    - country
    - city
    - region
    - street
    - postal_code
  audit_columns:
    start_date: __START_AT
    end_date: __END_AT
    is_current: is_current
